### PR TITLE
Update yafc-ce to 2.0.1

### PR DESCRIPTION
**Pull request by TheColorman**
Hey @diamond-deluxe, I accidentally opened [an init pr](https://github.com/NixOS/nixpkgs/pull/351128) for yafc-ce 2.0.0 before realising that [you'd already](https://github.com/NixOS/nixpkgs/pull/335230) opened a similar PR (but for v0.9.1). I noticed that your PR hasn't been very active, so I'm hoping to transfer my PR to your fork so I can spark some life into it again.

I'd also like to add myself as a maintainer as I have an interest in keeping it up to date.

If you agree I'll add some commits to my branch to get it to merge nicely here, and then I'll poke to the reviewers over at your PR.

### CODE REVIEW

**Comment by TheColorman** [comment]
If you don't respond I'll attempt to get my 2.0.0 init through directly to nixpkgs as it seems a bit silly to merge a 0.9.1 version only to immediately update it to 2.0.0

**Comment by diamond-deluxe** [comment]
Hey, this looks great, thanks! Fingers crossed the PR on the upstream gets some attention now :crossed_fingers:

**Comment by TheColorman** [comment]
> Hey, this looks great, thanks! Fingers crossed the PR on the upstream gets some attention now 🤞

Awesome! Just make sure to squash the commits again so there's only 1 `init` commit.

**Comment by diamond-deluxe** [comment]
Just done so :)

**Comment by TheColorman** [comment]
Nice, here's to hoping it gets some attention as you said.

**Pull request merged**
